config/routes.rb
Rails.application.routes.draw do

  get 'student_informations/search'
  post 'search_result'=> 'student_informations#search_result'

  root 'student_informations#new'

    resources :student_informations

end

app/models/student_information.rb
class StudentInformation < ActiveRecord::Base
	validates :name , :father_name,:address, presence: true, length: {minimum: 5}
	#validates :sex , presence: true ,length: {minimum: 3}
	validates :email_id ,:contact_no, presence: true ,length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/student_informations_controller.rb
class StudentInformationsController < ApplicationController
  def index
     @studentinfo=StudentInformation.all
  end

  def edit
    @studentinfo=StudentInformation.find(params[:id])
  end
  
  def new
      @studentinfo=StudentInformation.new
  end


  def create
  	@studentinfo=StudentInformation.new(student_params)
  	if @studentinfo.save
  	redirect_to action: :show, :id => @studentinfo.id
    else 
    render 'new'
    end  
  end

  def update
  @studentinfo = StudentInformation.find(params[:id])
 
    if @studentinfo.update(student_params)
    redirect_to student_informations_path(@studentinfo.id)
    else
    render 'edit'
    end
  end

  def search
  end

  def search_result
    @studentinfo=StudentInformation.find_by_name(params[:name])
    render 'search'
  end  
  
  def destroy
      @studentinfo=StudentInformation.find(params[:id])
      @studentinfo.destroy
      redirect_to :action => 'index'
  end

  def show
    @studentinfo=StudentInformation.find(params[:id])
  end

  private 
  
  def student_params
      params.require(:student_information).permit(:name,:father_name,:sex,:address,:email_id,:contact_no)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/student_informations_helper.rb
module StudentInformationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudentInfoCenter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/student_informations/_form.html.erb
<% if @studentinfo.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@studentinfo.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @studentinfo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table border=0.5 >
<tr> <td> <%= f.label :name %> </td>
	<td>  <%= f.text_field :name %></td>
</tr>
<tr> <td> <%= f.label :father_name, "Father's Name"%> </td>
	<td>  <%= f.text_field :father_name %></td>
</tr>
<tr> <td> <%= f.label :sex %> </td>
	<td>  <%= f.text_field :sex %></td>
</tr>
<tr> <td> <%= f.label :address %> </td>
	<td>  <%= f.text_area :address %></td>
</tr>
<tr> <td> <%= f.label :email_id %></td>
	<td>  <%= f.text_field :email_id %></td>
</tr>
<tr> <td> <%= f.label :contact_no %> </td>
	<td>  <%= f.text_field :contact_no %></td>
</tr>
</table>
<h2> <%= f.submit :SUBMIT %> </h2>

app/views/student_informations/edit.html.erb
<h1>Edit the Student Informations Details</h1>
<%= form_for @studentinfo, url: student_information_path(@studentinfo.id), method: :patch do |f| %>
 
  <%= render :partial => 'form', locals: {:f => f} %>
 
<% end %>
 
<%= link_to 'Back', student_informations_path %>

app/views/student_informations/index.html.erb
<h1>List of Students Informations</h1>

<table border=0.5 >
	<tr>
		<th>Name </th>
		<th>Father's Name</th>
		<th>Sex </th>
		<th>Address </th>
		<th>Email_id></th>
		<th>Contact_no</th>
    </tr>
    <% @studentinfo.each do |studentinfo| %>
      <tr> 
	    <td>  <%= studentinfo.name %></td>
      <td>  <%= studentinfo.father_name %></td>
      <td>  <%= studentinfo.sex %></td>
      <td>  <%= studentinfo.address %></td>
      <td>  <%= studentinfo.email_id %></td>
      <td>  <%= studentinfo.contact_no %></td>
      <td><%= link_to 'Show', student_information_path(studentinfo.id) %></td>
      <td><%= link_to 'Edit', edit_student_information_path(studentinfo.id) %></td>
      <td><%= link_to 'destroy',student_information_path(studentinfo.id), method: 'delete', 
                      data: { confirm: 'Are you sure want to delete the student data?' }%>
      </td>
      </tr>
    <% end %>
</table>

app/views/student_informations/new.html.erb
<center><h1><u>Student Informations</u></h1>
<%= form_for @studentinfo , url: student_informations_path do |f| %>
<%= render :partial => 'form', locals: {:f => f} %>


<% end %>
<p>
  <%=link_to 'View all' ,student_informations_path %>
</p>

<p>
  <%=link_to 'Search Student details' ,search_result_path %>
</p>
</center>

app/views/student_informations/search.html.erb
<%= form_tag search_result_path do %>
      <h1>Enter the name of Students</h1>
	  <p> 
		<p> <%= label_tag :name %> 
			<%= text_field_tag :name %>
	  </p>
      <h2> <%= submit_tag :SUBMIT %> </h2>
    <% end %>

    <% if @studentinfo.present? %> 
    <table>
    <tr>
    	<td>  <%= @studentinfo.name %></td>
        <td>  <%= @studentinfo.father_name %></td>
        <td>  <%= @studentinfo.sex %></td>
        <td>  <%= @studentinfo.address %></td>
        <td>  <%= @studentinfo.email_id %></td>
        <td>  <%= @studentinfo.contact_no %></td>
    </tr>
  
</table>
<% end %>

app/views/student_informations/show.html.erb
<h1>Data saved successfully</h1>

<h1> The Details of all the students is as follows</h1>
<p>
  <strong>Name:</strong>
  <%= @studentinfo.name %>
</p>
 
<p>
  <strong>Father's Name:</strong>
  <%= @studentinfo.father_name %>
</p>
<p>
  <strong>Sex:</strong>
  <%= @studentinfo.sex %>
</p>
<p>
  <strong>Address:</strong>
  <%= @studentinfo.address %>
</p>
<p>
  <strong>Email_id:</strong>
  <%= @studentinfo.email_id %>
</p>
<p>
  <strong>Contact_no:</strong> 
  <%= @studentinfo.contact_no %>
</p>
<p>
  <%=link_to 'View all' ,'/student_informations' %>
</p>
<p>
<%= link_to 'Back' ,'/student_informations/new' %>
</p>